services:
  lutheran-lectionary:
    image: ghcr.io/abc3-mac/lutheran-lectionary:latest
    container_name: lutheran-lectionary
    restart: unless-stopped
    ports:
      - "5765:5765"
    environment:
      FLASK_ENV: production
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5765
    networks:
      - npm_npm_network

networks:
  npm_npm_network:
    external: true
